version: "3"
services:

    
  streamlit:
    build:
      context: ./code/streamlit
      dockerfile: Dockerfile
    container_name: streamlit-image
    volumes:
    - ./code:/code  # lisätty rivi
    ports:
    - 8501:8501
    networks:
      - jupyterhub-network
      

  jupyter-workshop:
    image: jupyter-workshop
    build: 
      context: ./code/jupyter_workshop
      dockerfile: Dockerfile
    container_name: jupyter-workshop
    volumes:
      - ./code:/home/jovyan/work
    ports:
      - 8889:8888
    environment:
      - JUPYTER_TOKEN=daika
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - jupyterhub-network

    

networks:
  jupyterhub-network:
    external: false