version: "3"
services:

    
  streamlit:
    build:
      context: ./code/streamlit
      dockerfile: Dockerfile
    container_name: streamlit-image
    volumes:
    - ./code:/code
    ports:
    - 8501:8501
    networks:
      - jupyterhub-network
      

    

networks:
  jupyterhub-network:
    external: false